<?php $purchaseOrderId = $this->getPurchaseorderid(); ?>
<?php $items = $this->getSqlnews() ?>
<?php
$purchaseOrder = Mage::getModel('supplier/purchaseorder')->load($purchaseOrderId);
$currency = $purchaseOrder->getCurrency();
$purchaseOrderProducts = Mage::getModel('supplier/purchaseorder_product')
        ->getCollection()
        ->addFieldToFilter('purchase_order_id', $purchaseOrderId);
$supplierInfo = Mage::helper('supplier/purchaseorder')->getSupplierInfoByPurchaseOrderId($purchaseOrderId);

$taxRate = $purchaseOrder->getTaxRate();
$shippingCost = $purchaseOrder->getShippingCost();
$totalBase = 0;
?>
<table cellspacing="0" cellpadding="0" border="0" width="650" style="font-family:Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
    <tr>
<!--        <td valign="top">-->
<!--            <i>--><?php //echo $this->__('Return From') ?><!--</i><br />-->
<!--        </td>-->
        <td valign="top">
            <i><?php echo $this->__('To') ?></i><br />
            <strong><?php echo $purchaseOrder->getSupplierName() ?></strong>
            <?php echo $supplierInfo ?>
        </td>
        <td valign="top">
            <i><?php echo $this->__('Purchase Order') ?></i><br />
            <?php echo $this->__('P.O.No#: ') . $purchaseOrder->getId() ?><br />
            <?php echo $this->__('Order created on: ') . $this->formatDate($purchaseOrder->getPurchaseOn(), 'short') ?><br />
        </td>
    </tr>
</table>
<br/>
<h3><?php echo Mage::helper('supplier')->__('All products are returned to supplier'); ?></h3>
<table cellspacing="0" cellpadding="0" border="0" width="650" style="font-family: Arial, Helvetica, sans-serif; border:1px solid #EAEAEA;">
    <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Product') ?></th>
            <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('SKU') ?></th>
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Cost') ?></th>                                           
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Tax(%)') ?></th>                                           
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Discount(%)') ?></th>                                           
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Supplier SKU') ?></th>
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Qty Returned') ?></th>
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Amount') ?></th>
        </tr>
    </thead>
    <?php
        $subtotal = 0;
        $shippingCost = $purchaseOrder->getShippingCost();
        $tax = 0;
        $discountTax = $purchaseOrder->getDiscountTax();
        $shippingTax = $purchaseOrder->getShippingTax();
    ?>
    <?php $i = 0;
    foreach ($items as $item): ?>            
        <tbody<?php echo $i % 2 ? ' bgcolor="#F6F6F6"' : '' ?>>
            <tr>
                <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
                    <strong style="font-size:11px;"><?php echo $this->htmlEscape($item["product_name"]) ?></strong>                        
                </td>
                <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
                    <?php echo $this->htmlEscape($item["product_sku"]) ?>
                </td>
                <td align="center" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
                    <?php echo Mage::getModel('directory/currency')->load($currency)->formatTxt($item["cost"]) ?>
                </td>                                        
                <td align="center" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
                    <?php echo $item["tax"] ?>
                </td>                                        
                <td align="center" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
                    <?php echo $item["discount"] ?>
                </td>
                <td align="center" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
                    <?php echo $item["supplier_sku"] ?>
                </td>
                <td align="center" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
                    <?php echo $item["qty_returned"] ?>
                </td>
                <td align="center" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
                    <span class="price">
                         <?php
                             $subtotal += ($item["qty_returned"]) * $item["cost"] * (1 - $item["discount"]/100);
                             if($discountTax == 0){
                                 $amount = ($item["qty_returned"]) * $item["cost"] * (1+ $item["tax"]/100 - $item["discount"]/100);
                                 $tax += ($item["qty_returned"]) * $item["cost"] * ($item["tax"]/100);
                             }else{
                                 $amount = ($item["qty_returned"]) * $item["cost"] * (1 - $item["discount"]/100) * (1 + $item["tax"]/100);
                                 $tax += ($item["qty_returned"]) * $item["cost"] * (1 - $item["discount"]/100) * ($item["tax"]/100);
                             }
                         ?>
                         <?php echo Mage::getModel('directory/currency')->load($currency)->formatTxt($amount) ?>
                    </span>
                </td>
            </tr>
        </tbody>
        <?php $i++; ?>
        <?php //$totalBase += $item["cost"] * (1 + $item["tax"] / 100 - $item["discount"] / 100) * ($item["qty_returned"]); ?>
    <?php endforeach; ?>
    <?php
//        if($shippingTax == 0){
//            $tax += $shippingCost * ($item["tax"]/100);
//        }
        $grandTotalExc = $subtotal;
        $grandTotalInc = $subtotal + $tax;
    ?>
</table>   
<?php //$totalWithTaxBase = (1 + $taxRate / 100) * $totalBase; ?>
<div class="order-totals" style="font-family: Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;float: right;text-align: right;width: 48%;">
    <table width="100%" cellspacing="0" style="font-family: Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
        <colgroup>
            <col>
            <col width="1">
        </colgroup>        
        <tbody>
            <tr class="0">
                <td class="label">
                    <strong><?php echo $this->__('Subtotal (excl. Tax)') ?></strong>
                </td>
                <td class="emph">
                    <strong><span class="price"><?php echo Mage::getModel('directory/currency')->load($currency)->formatTxt($subtotal) ?></span></strong>
                </td>
            </tr>
            <tr class="0">
                <td class="label">
                    <strong><?php echo $this->__('Tax'); ?></strong>
                </td>
                <td class="emph">
                    <strong><span class="price"><?php echo Mage::getModel('directory/currency')->load($currency)->formatTxt($tax); ?></span></strong>
                </td>
            </tr>
            <tr class="1">
                <td class="label">
                    <strong><?php echo $this->__('Grand Total (excl. Tax)') ?></strong>
                </td>
                <td class="emph">
                    <strong><span class="price"><?php echo Mage::getModel('directory/currency')->load($currency)->formatTxt($grandTotalExc) ?></span></strong>
                </td>
            </tr>
            <tr class="2">
                <td class="label">
                    <strong><?php echo $this->__('Grand Total (incl. Tax)') ?></strong>
                </td>
                <td class="emph">
                    <strong><span class="price"><?php echo Mage::getModel('directory/currency')->load($currency)->formatTxt($grandTotalInc) ?></span></strong>
                </td>
            </tr>
        </tbody>
    </table>
    <div style="clear:both"></div>
    <!--<a href="#" onclick="myFunction()"><?php echo $this->__('Print this page') ?></a>
    <script>
        function myFunction() {
            window.print();
        }
    </script>-->
</div>